In [2]:
import pandas as pd

In [3]:
! ls

chiffres-cles.csv  example.ipynb  example.txt

In [5]:
df = pd.read_csv("./chiffres-cles.csv")

/opt/conda/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (17,18) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [6]:
df.head()

,date,granularite,maille_code,maille_nom,cas_confirmes,cas_ehpad,cas_confirmes_ehpad,cas_possibles_ehpad,deces,deces_ehpad,reanimation,hospitalises,nouvelles_hospitalisations,nouvelles_reanimations,gueris,depistes,source_nom,source_url,source_archive,source_type
0,2020-01-24,departement,DEP-16,Charente,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
1,2020-01-24,departement,DEP-17,Charente-Maritime,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
2,2020-01-24,departement,DEP-19,Corrèze,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
3,2020-01-24,departement,DEP-23,Creuse,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
4,2020-01-24,departement,DEP-24,Dordogne,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante

In [7]:
df.describe()

,cas_confirmes,cas_ehpad,cas_confirmes_ehpad,cas_possibles_ehpad,deces,deces_ehpad,reanimation,hospitalises,nouvelles_hospitalisations,nouvelles_reanimations,gueris,depistes
count,3.003000e+03,49.000000,235.000000,15.000000,33568.000000,249.000000,32385.000000,32467.000000,31737.000000,31737.000000,32353.000000,49.000000
mean,4.956855e+04,68314.959184,47699.021277,35228.000000,617.376400,10535.590361,71.814544,487.176672,27.829064,4.387623,2638.845486,462.204082
std,2.442747e+05,9760.158846,22298.228077,5673.218474,2679.836483,2552.710174,386.515534,2361.208457,162.272659,26.214918,11592.430962,292.182519
min,0.000000e+00,37188.000000,11958.000000,25230.000000,0.000000,371.000000,0.000000,0.000000,0.000000,0.000000,0.000000,15.000000
25%,5.000000e+00,67168.000000,37599.000000,32238.500000,24.000000,10350.000000,2.000000,15.000000,0.000000,0.000000,134.000000,231.000000
50%,2.500000e+01,72548.000000,39645.000000,37379.000000,82.000000,10506.000000,7.000000,58.000000,2.000000,0.000000,391.000000,479.000000
75%,1.830000e+02,74402.000000,46110.500000,38896.500000,268.000000,10785.000000,26.000000,211.000000,12.000000,2.000000,1188.000000,650.000000
max,2.292497e+06,74516.000000,119716.000000,40726.000000,37996.000000,17159.000000,7148.000000,33497.000000,4281.000000,771.000000,169586.000000,1261.000000

In [10]:
df_dpt = df[df["granularite"]=="departement"]
df_dpt.head()

,date,granularite,maille_code,maille_nom,cas_confirmes,cas_ehpad,cas_confirmes_ehpad,cas_possibles_ehpad,deces,deces_ehpad,reanimation,hospitalises,nouvelles_hospitalisations,nouvelles_reanimations,gueris,depistes,source_nom,source_url,source_archive,source_type
0,2020-01-24,departement,DEP-16,Charente,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
1,2020-01-24,departement,DEP-17,Charente-Maritime,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
2,2020-01-24,departement,DEP-19,Corrèze,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
3,2020-01-24,departement,DEP-23,Creuse,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante
4,2020-01-24,departement,DEP-24,Dordogne,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ARS Nouvelle-Aquitaine,https://www.nouvelle-aquitaine.ars.sante.fr/co...,NaN,agences-regionales-sante

In [11]:
df_dpt.describe()

,cas_confirmes,cas_ehpad,cas_confirmes_ehpad,cas_possibles_ehpad,deces,deces_ehpad,reanimation,hospitalises,nouvelles_hospitalisations,nouvelles_reanimations,gueris,depistes
count,1649.000000,0.0,0.0,0.0,27825.000000,0.0,26908.000000,26971.000000,26563.000000,26563.000000,26897.000000,6.000000
mean,38.085506,NaN,NaN,NaN,184.652543,NaN,21.443920,146.752623,9.297444,1.472876,793.592780,579.666667
std,76.077147,NaN,NaN,NaN,302.020322,NaN,48.559604,271.530766,21.859091,4.090724,1250.491112,165.928499
min,0.000000,NaN,NaN,NaN,0.000000,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,349.000000
25%,3.000000,NaN,NaN,NaN,23.000000,NaN,1.000000,13.000000,0.000000,0.000000,124.000000,484.250000
50%,10.000000,NaN,NaN,NaN,72.000000,NaN,5.000000,48.000000,2.000000,0.000000,320.000000,575.000000
75%,39.000000,NaN,NaN,NaN,184.000000,NaN,19.000000,151.000000,8.000000,1.000000,814.000000,687.500000
max,827.000000,NaN,NaN,NaN,2529.000000,NaN,855.000000,3281.000000,404.000000,96.000000,10320.000000,800.000000